### ISSUE TITLE
build never exists

### ISSUE THREAD

**Issue by lukescott** [gobblejs/gobble-cli#12]
`gobble build dest` never exists. This is a big problem for CI tools.

**Comment by Rich-Harris** [comment]
Not sure I follow - if the build is working correctly, it should create `dest` automatically. Is that not happening?

**Comment by Rich-Harris** [comment]
Oh, scratch that, I understand what you mean now. Duh.

**Comment by Rich-Harris** [comment]
Can close this now - thanks for getting to the bottom of it
