### ISSUE TITLE
Invalid array length

### ISSUE THREAD

**Issue by Rich-Harris** [gobblejs/gobble-cli#13]
Via https://github.com/gobblejs/gobble/issues/60. Just about to start poking about, haven't quite figured out what's going on yet, but somehow gobble-cli is trying to create an array of negative length. @evs-chris does this ring any bells?

**Comment by evs-chris** [comment]
I fixed one of those in the last PR. There was a problem with the blanking if your console was smaller than the message. I'll poke about a bit. Hopefully I didn't completely derp it.

**Comment by Rich-Harris** [comment]
Ah, great, I knew you'd know the answer! @martypdx I found a pretty good workaround in the meantime - make your terminal bigger :laughing:

**Comment by Rich-Harris** [comment]
Just released 0.4.1 with @evs-chris' fix
