### ISSUE TITLE
could not find a local copy of gobble

### ISSUE THREAD

**Issue by fskreuz** [gobblejs/gobble-cli#20]
I'm getting this error after updating gobble up to 0.11 on two separate projects (it's more than just a coincidence now :smile: )

```
gobble: could not find a local copy of gobble. You should probably install it with npm install --save-dev gobble
```

Versions:
```
node: 5.11.0
npm: 3.8.6
gobble-cli: 0.6.0
gobble: 0.11.0
```

After some digging, I found [this line as the culprit](https://github.com/gobblejs/gobble-cli/blob/master/lib/index.js#L82).

```js
		if ( !env.modulePath ) {
			logger.error({
				name: 'GobbleError',
				code: 'MISSING_GOBBLE'
			});
			process.exit( 1 );
		}
```
Seems like Liftoff isn't providing `env.modulePath`.

**Comment by Rich-Harris** [comment]
Huh, that's weird... are you using a globally installed `gobble-cli` (i.e. typing `gobble`) or a local one (i.e. `npm run build` etc)?

**Comment by fskreuz** [comment]
I actually tried both local (run via `npm run something`) and global (run via `gobble`). Both don't seem to work. I'm on Windows. With [the silly things I've seen today](https://github.com/gobblejs/gobble/issues/108), may be possible that it's just broken on my machine. But I wanted to verify :smile: .

**Comment by IvanSanchez** [comment]
Closing in favour of https://github.com/gobblejs/gobble/pull/109
